New upstream release: Alpha 27 Agni.
Rebase on core24 and use the mesa-2404 content snap as a provider for GPU capabilities.
Remove the process-control plug requirement, the game doesn't fail to start/run without setpriority.

diff --git a/patches/allow-build-with-root.patch b/patches/allow-build-with-root.patch
--- a/patches/allow-build-with-root.patch
+++ b/patches/allow-build-with-root.patch
@@ -1,7 +1,7 @@
 Description: Allow building 0ad as root/fakeroot
-Forwarded: no
+Forwarded: not-needed
 Author: Rico Tzschichholz <ricotz@ubuntu.com>
-Last-Update: 2014-10-13
+Last-Update: 2025-02-01
 
 --- a/build/workspaces/update-workspaces.sh
 +++ b/build/workspaces/update-workspaces.sh
@@ -9,10 +9,10 @@ Last-Update: 2014-10-13
  #!/bin/sh
  
 -if [ "$(id -u)" = "0" ]; then
--   echo "Running as root will mess up file permissions. Aborting ..." 1>&2
--   exit 1
+-	echo "Running as root will mess up file permissions. Aborting ..." 1>&2
+-	exit 1
 -fi
 -
  die()
  {
-   echo ERROR: $*
+ 	echo ERROR: "$*"
